<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.5 on win32)" generated="20210119 16:08:48.918" rpa="false">
<suite id="s1" name="restApi tests" source="C:\Users\op671200\Documents\GitHub\TestingToDoList\RestAPI\restApi_tests.robot">
<test id="s1-t1" name="TC - Verify GET API call">
<kw name="Get method execution">
<msg timestamp="20210119 16:08:48.966" level="FAIL">No keyword with name 'Get method execution' found.</msg>
<status status="FAIL" starttime="20210119 16:08:48.966" endtime="20210119 16:08:48.966"></status>
</kw>
<status status="FAIL" starttime="20210119 16:08:48.965" endtime="20210119 16:08:48.967" critical="yes">No keyword with name 'Get method execution' found.</status>
</test>
<status status="FAIL" starttime="20210119 16:08:48.922" endtime="20210119 16:08:48.969"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="restApi tests">restApi tests</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210119 16:08:48.962" level="ERROR">Error in file 'C:\Users\op671200\Documents\GitHub\TestingToDoList\RestAPI\restApi_tests.robot' on line 2: Resource file '..\..\RestAPI\restAPI_keywords.py' does not exist.</msg>
</errors>
</robot>
